/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package es.vass.demo.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Hero service. Represents a row in the &quot;datahandler_Hero&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.vass.demo.service.model.impl.HeroModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.vass.demo.service.model.impl.HeroImpl}.
 * </p>
 *
 * @author diego.failde
 * @see Hero
 * @see es.vass.demo.service.model.impl.HeroImpl
 * @see es.vass.demo.service.model.impl.HeroModelImpl
 * @generated
 */
public interface HeroModel extends BaseModel<Hero>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hero model instance should use the {@link Hero} interface instead.
	 */

	/**
	 * Returns the primary key of this hero.
	 *
	 * @return the primary key of this hero
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hero.
	 *
	 * @param primaryKey the primary key of this hero
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this hero.
	 *
	 * @return the uuid of this hero
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this hero.
	 *
	 * @param uuid the uuid of this hero
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the hero ID of this hero.
	 *
	 * @return the hero ID of this hero
	 */
	public long getHeroId();

	/**
	 * Sets the hero ID of this hero.
	 *
	 * @param heroId the hero ID of this hero
	 */
	public void setHeroId(long heroId);

	/**
	 * Returns the group ID of this hero.
	 *
	 * @return the group ID of this hero
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this hero.
	 *
	 * @param groupId the group ID of this hero
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this hero.
	 *
	 * @return the company ID of this hero
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this hero.
	 *
	 * @param companyId the company ID of this hero
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this hero.
	 *
	 * @return the user ID of this hero
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this hero.
	 *
	 * @param userId the user ID of this hero
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this hero.
	 *
	 * @return the user uuid of this hero
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this hero.
	 *
	 * @param userUuid the user uuid of this hero
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this hero.
	 *
	 * @return the user name of this hero
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this hero.
	 *
	 * @param userName the user name of this hero
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this hero.
	 *
	 * @return the create date of this hero
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this hero.
	 *
	 * @param createDate the create date of this hero
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this hero.
	 *
	 * @return the modified date of this hero
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hero.
	 *
	 * @param modifiedDate the modified date of this hero
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this hero.
	 *
	 * @return the name of this hero
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this hero.
	 *
	 * @param name the name of this hero
	 */
	public void setName(String name);

	/**
	 * Returns the description of this hero.
	 *
	 * @return the description of this hero
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this hero.
	 *
	 * @param description the description of this hero
	 */
	public void setDescription(String description);

	/**
	 * Returns the image ID of this hero.
	 *
	 * @return the image ID of this hero
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this hero.
	 *
	 * @param imageId the image ID of this hero
	 */
	public void setImageId(long imageId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(es.vass.demo.service.model.Hero hero);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.vass.demo.service.model.Hero> toCacheModel();

	@Override
	public es.vass.demo.service.model.Hero toEscapedModel();

	@Override
	public es.vass.demo.service.model.Hero toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}