/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package es.vass.demo.service.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import es.vass.demo.service.model.Hero;
import es.vass.demo.service.service.HeroLocalServiceUtil;

/**
 * The extended model base implementation for the Hero service. Represents a row in the &quot;datahandler_Hero&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HeroImpl}.
 * </p>
 *
 * @author diego.failde
 * @see HeroImpl
 * @see es.vass.demo.service.model.Hero
 * @generated
 */
public abstract class HeroBaseImpl extends HeroModelImpl implements Hero {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hero model instance should use the {@link Hero} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			HeroLocalServiceUtil.addHero(this);
		}
		else {
			HeroLocalServiceUtil.updateHero(this);
		}
	}
}